### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Yoshito21** [Yoshito21/protospace-38911#1]
https://protospace-38911.onrender.com

半日かけてやっとデプロイができました。
よろしくお願いいたします。

**Comment by ghost** [comment]
@Yoshito21 さん　ご提出いただきありがとうございます。
先ほどslackのgeneralのチャンネルにご案内しました通り、
現在、renderでの不具合が起こっており、ご提出いただいたアプリの挙動確認ができておりません。

generalのチャンネルのご案内に、「対応方法」と「現在、ご提出頂いている受講生様に行っていただきたいこと」のご案内を差し上げておりますため、ご確認とご対応いただき、
以下のProtoSpace完了報告フォームのご提出をお願いします。
お手数をおかけしますが、何卒よろしくお願い致します。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by ghost** [comment]
@Yoshito21 さん、ご提出ありがとうございます‼︎
https://protospace-38911.onrender.com/　
にアクセスをし動作の確認をしたところ、エラー画面が表示され挙動確認ができない状態です。
今一度、本番環境でアプリが開けるかをご確認いただき、
以下のProtoSpace完了報告フォームのご提出をお願いします。
※質問等でコメントした場合も都度フォームのご提出をお願いします。

https://forms.gle/ZdLeprTTWhMA8aZA7
